services:
  api:
    image: mcr.microsoft.com/dotnet/sdk:10.0
    container_name: concurrent_job_processor

    volumes:
      - .:/workspace

    working_dir: /workspace

    environment:
      ASPNETCORE_URLS: http://+:5000
      ASPNETCORE_ENVIRONMENT: Development

    command: dotnet run --no-launch-profile

    depends_on:
      - postgres

    env_file:
      - .env

    ports:
      - "5000:5000"
      - "5001:5001"

  postgres:
    image: postgis/postgis:16-3.4

    container_name: postgres

    restart: unless-stopped

    env_file:
      - .env

    ports:
      - "${POSTGRES_PORT}:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: